Списки (list) в Python нельзя напрямую складывать с числами (Python 中的列表不能直接与数字相加)

In [1]:
a = [1, 2, 3, 4]
# a + 1

In [2]:
[x + 1 for x in a]

[2, 3, 4, 5]

Оператор `a + b` соединяет два списка, а не складывает их элементы поэлементно (运算符 `a + b` 将两个列表连接起来，而不是元素的逐个相加)

In [3]:
b = [2, 3, 4, 5]
a + b

[1, 2, 3, 4, 2, 3, 4, 5]

In [4]:
[x + y for (x, y) in zip(a, b)]

[3, 5, 7, 9]

NumPy позволяет делать такие операции проще и быстрее по сравнению с обычными списками Python!

NumPy 使这些操作比普通的 Python 列表更容易、更快速！

Чтобы использовать NumPy, сначала нужно его импортировать (要使用 NumPy，首先需要导入它)

In [5]:
import numpy as np

## 1. NumPy
NumPy поддерживает поэлементные операции с массивами (NumPy支持对数组进行逐元素运算)

In [6]:
# NumPy автоматически распространяет скаляр на все элементы массива (NumPy 会自动将标量传播到数组的所有元素)
a = np.array([1, 2, 3, 4])
a + 1

array([2, 3, 4, 5])

In [7]:
b = np.array([2, 3, 4, 5])
a + b

array([3, 5, 7, 9])

NumPy поддерживает гибкую систему *broadcasting* — если формы массивов совместимы, то меньший массив «растягивается» по измерениям большего (NumPy 支持灵活的广播机制：当数组形状兼容时，较小的数组会在需要的维度上自动“扩展”，与较大的数组进行逐元素运算)

In [8]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([1, 2, 3])
a + b

array([[2, 4, 6],
       [5, 7, 9]])

## 2. Инициализация массивов (数组初始化)

### 2.1 `np.array([list])`
Создание массива из списка (从列表创建数组)

In [9]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [10]:
a = np.array([1.0, 2.0, 3.0, 4.0])
a

array([1., 2., 3., 4.])

### 2.2 `np.zeros(N)` и `np.ones(N)`
Создание массивов из нулей и единиц (创建由 0 或 1 组成的数组)
По умолчанию используется тип float64, но можно указать другой (默认类型为 float64，但可以指定其他类型)

In [11]:
np.zeros(4)

array([0., 0., 0., 0.])

In [12]:
np.ones(4)

array([1., 1., 1., 1.])

In [13]:
np.zeros(4, dtype="int32")

array([0, 0, 0, 0], dtype=int32)

In [14]:
np.ones(4, dtype="bool")

array([ True,  True,  True,  True])

### 2.3 `np.fill()`
Заполняет все элементы массива заданным значением.

In [15]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [16]:
a.fill(5)
a

array([5, 5, 5, 5])

In [17]:
a.fill(2.5)
a

array([2, 2, 2, 2])

In [18]:
a = a.astype("float")
a.fill(2.5)
a

array([2.5, 2.5, 2.5, 2.5])

### 2.4 `np.arange(start, stop, step)`
Создание числового массива с заданным шагом  (按指定步长创建数组)
- start — начало (включается), по умолчанию 0  (起始值（包含），默认为 0)
- stop — конец (не включается)  (终止值（不包含）)
- step — шаг (может быть отрицательным)  (步长（可以为负数）)

In [19]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [22]:
np.arange(10, 1, -2)

array([10,  8,  6,  4,  2])

### 2.5 `np.linspace(start, stop, num)`
Создание массива из заданного числа точек на отрезке (在给定区间上生成指定个数的点)
- `start`, `stop` — начало и конец отрезка (默认情况下，两端都包含)
- `num` — число точек (по умолчанию `50`)  (生成点的个数 (默认 50))
- `endpoint` — по умолчанию `True` (включать `stop` или нет)  (是否包含终点 `stop`，默认为 `True`)
- `retstep=True` — дополнительно возвращает шаг между точками  (若为 True，会同时返回点与相邻两点之间的步长)

In [23]:
np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [24]:
np.linspace(1, 10, 10, dtype=int)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
a, step = np.linspace(1, 10, 10, retstep=True)

In [26]:
a

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [27]:
step

np.float64(1.0)

### 2.6 Через списковые выражения (通过列表表达式)

#### Пример 1: линейное приращение (线性递增)

In [28]:
a = np.array([1 + i for i in range(10)])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### Пример 2: квадратичное приращение (二次递增)

In [29]:
a = np.array([(1 + i)**2 for i in range(10)])
a

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

#### Пример 3: двумерный массив через вложенные циклы (通过嵌套循环创建二维数组)

In [30]:
a = np.array([[i * j for j in range(4)] for i in range(3)])
a

array([[0, 0, 0, 0],
       [0, 1, 2, 3],
       [0, 2, 4, 6]])

### 2.7 Генерация случайных чисел (生成随机数)

2.7.1 `np.random.rand(n)`: равномерное распределение на $[0, 1]$  
(在 $[0, 1]$ 上服从均匀分布)

In [31]:
a = np.random.rand(10)
a

array([0.30551292, 0.89365342, 0.81740974, 0.29045673, 0.88146666,
       0.01731485, 0.23800293, 0.70616683, 0.83983079, 0.33500578])

2.7.2 `np.random.randn(n)`: нормальное распределение со средним 0 и отклонением 1  
(均值为 0，标准差为 1 的正态分布)

In [32]:
b = np.random.randn(10)
b

array([ 0.75158379, -1.15829155, -0.02208693,  0.54480907,  0.26572946,
       -0.79823051,  2.08340721, -1.2307884 , -1.21986904, -0.8909454 ])

2.7.3 `np.random.randint(low, high, size)`: случайные целые числа  
(随机整数)

In [33]:
c = np.random.randint(1, 20, 10)
c

array([ 2,  1,  5,  9,  2, 10,  2, 13,  3, 18])

2.7.4 `np.random.normal(loc, scale, size)`: нормальное распределение с центром `loc` и отклонением `scale`  
(中心为 `loc`，标准差为 `scale` 的正态分布)

In [34]:
d = np.random.normal(0, 1, 10)
d

array([ 0.12684244,  1.34739487,  0.23678587, -0.1664979 ,  0.07710066,
       -1.48856945, -0.88603035, -0.40628706,  0.44360176,  0.76445388])

2.7.5 `np.random.choice(a, size, replace=True)`: выбор случайных элементов из массива `a`  
(从数组 `a` 中选择随机元素)

In [35]:
a = np.array([1,2,3,4,5,6,7,8,9])
np.random.choice(a, 3)

array([3, 8, 7])

## 3. Свойства массива NumPy (Numpy 数组的性质)
- `type(a)` — тип объекта (对象的类型)
- `a.dtype` — тип данных внутри массива (数组内部元素的数据类型)
- `a.shape` — форма массива (возвращает кортеж, указывающий размерность по каждой оси) (数组的形状，返回一个元组，表示每一维的长度)
- `a.size` — общее количество элементов в массиве (元素总个数)
- `a.ndim` — количество измерений (размерность массива) (维数)

In [36]:
a = np.array([1, 2, 3, 4, 5])
a = np.array([[1, 2, 3],[4, 5, 6]])
a = np.array([[[1, 2, 3],[4, 5, 6]],[[2, 3, 4],[5, 6, 7]]])
a

array([[[1, 2, 3],
        [4, 5, 6]],

       [[2, 3, 4],
        [5, 6, 7]]])

In [37]:
type(a)

numpy.ndarray

In [38]:
a.dtype

dtype('int64')

In [39]:
a.shape

(2, 2, 3)

In [40]:
a.size

12

In [41]:
a.ndim

3

> `a.shape`, `a.size`, `a.ndim` — только для NumPy массивов  
> `np.shape(a)`, `np.size(a)`, `np.ndim(a)` — применимы к массивам и другим структурам (например, спискам, кортежам)

In [42]:
a = [[1, 2, 3, 4], [2, 4, 6, 8]]
np.shape(a)

(2, 4)

## 4. Индексация и срезы массивов (数组索引和切片)

### 4.1 Одномерный массив (一维数组)

In [43]:
a = np.array([1,2,3,4,5,6])

In [44]:
a[1:3]

array([2, 3])

In [45]:
a[1:-2]

array([2, 3, 4])

In [46]:
a[::2]

array([1, 3, 5])

In [47]:
a[0] = 10
a

array([10,  2,  3,  4,  5,  6])

### 4.2 Двумерный массив (二维数组)

In [48]:
a = np.array([[0,1,2,3],
              [10,11,12,13]])

In [49]:
a[1,3]

np.int64(13)

In [50]:
a[1]

array([10, 11, 12, 13])

In [51]:
a[:,1]

array([ 1, 11])

In [52]:
a[1,3] = -1
a

array([[ 0,  1,  2,  3],
       [10, 11, 12, -1]])

### 4.3 Использование маски (掩码的使用)

In [53]:
a = np.arange(0, 10)

# Маска: элементы больше 5 (掩码：筛选出 > 5 的元素)
mask = (a > 5)
print(mask)

# Используем маску для выборки (用布尔掩码从数组中取出对应元素)
b = a[mask]
print(b)

[False False False False False False  True  True  True  True]
[6 7 8 9]


- NumPy использует ссылки при срезе — изменения в подмассиве влияют на исходный.
- Список Python копируется — оригинал не изменяется.
- Используйте copy() для создания независимого массива.

### * NumPy использует ссылки при срезе, изменения в подмассиве влияют на исходный  
(NumPy 在切片时使用引用，对子数组的更改会影响原始数组)

In [54]:
a = np.array([0,1,2,3,4])
b = a[2:4]
b[0] = 10
a

array([ 0,  1, 10,  3,  4])

### * Список копируется — оригинал не изменяется  
列表是复制的，原始列表保持不变

In [55]:
a = [1,2,3,4,5]
b = a[2:4]
b[0] = 10
a

[1, 2, 3, 4, 5]

### * Используйте copy() для создания независимого массива  
使用 copy() 创建一个独立的数组

In [56]:
a = np.array([0,1,2,3,4])
b = a[2:4].copy()
b[0] = 10
a

array([0, 1, 2, 3, 4])

## 5. Соединение и преобразование массивов 数组的连接与转换

### 5.1 Соединение массивов 数组连接

In [57]:
x = np.array([[0,1,2],
              [10,11,12]])
y = np.array([[50,51,52],
              [60,61,62]])

In [58]:
np.concatenate((x, y))  # по умолчанию axis=0 → "добавляем строки" (默认 axis=0：在“行”方向拼接)

array([[ 0,  1,  2],
       [10, 11, 12],
       [50, 51, 52],
       [60, 61, 62]])

In [59]:
np.concatenate((x, y), axis=1)  # axis=1 → "добавляем столбцы" (在“列”方向拼接)

array([[ 0,  1,  2, 50, 51, 52],
       [10, 11, 12, 60, 61, 62]])

In [60]:
np.array((x, y))  # Создаётся новый ось, x и y становятся двумя слоями (创建一个新的坐标轴，x和y变成了两层。)

array([[[ 0,  1,  2],
        [10, 11, 12]],

       [[50, 51, 52],
        [60, 61, 62]]])

In [61]:
np.vstack((x, y)) # Складывание по вертикали = concatenate(axis=0) (竖直堆叠，相当于 concatenate(axis=0))

array([[ 0,  1,  2],
       [10, 11, 12],
       [50, 51, 52],
       [60, 61, 62]])

In [62]:
np.hstack((x, y)) # Складывание по горизонтали = concatenate(axis=1) (水平堆叠，相当于 concatenate(axis=1))

array([[ 0,  1,  2, 50, 51, 52],
       [10, 11, 12, 60, 61, 62]])

### 5.2 Преобразование формы (形状变换)

In [65]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [67]:
a.shape = (2, 3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [68]:
a = np.arange(6)
b = a.reshape((2, 3))
b

array([[0, 1, 2],
       [3, 4, 5]])

In [69]:
a

array([0, 1, 2, 3, 4, 5])

In [70]:
b.T

array([[0, 3],
       [1, 4],
       [2, 5]])

### 5.3 Сортировка значений (排序)

In [76]:
data = np.array([3, 1, 4, 1, 5])
sorted_data = np.sort(data) # возвращает отсортированную копию массива, не изменяя исходный массив (返回排序后的新数组，不修改旧数组)
sorted_data

array([1, 1, 3, 4, 5])

In [77]:
data

array([3, 1, 4, 1, 5])

In [78]:
data.sort()   # сортировка на месте (in-place), изменяет сам массив (就地排序，直接改原数组)
data

array([1, 1, 3, 4, 5])

## 6. Скалярное произведение массивов（数组的点积）

In [ ]:
Операция `np.dot(A, B)` вычисляет скалярное произведение двух массивов
`np.dot(A, B)` 操作计算两个数组的点积。

In [83]:
A = np.array([1, 2, 3])
B = np.array([1, 100, 10000])

print(np.dot(A, B))

30201


## 7. Матричное произведение массивов （数组的矩阵乘积）

In [84]:
data1 = np.array([[1, 2, 3],
                  [4, 5, 6]])
data2 = np.array([[1, 2],
                  [3, 4],
                  [5, 6]])

print(np.matmul(data1, data2))

[[22 28]
 [49 64]]


## 8. Линейная алгебра (线性代数)

In [ ]:
A = np.array([[2.0, -1.0, 0.0],
              [-1.0, 2.0, -1.0],
              [0.0, -1.0, 2.0]])

In [85]:
print(np.linalg.det(A)) # Определитель матрицы (矩阵的行列式)

4.0


In [86]:
A_inverse = np.linalg.inv(A) # Обратная матрица (逆矩阵)
print(A_inverse)

[[0.75 0.5  0.25]
 [0.5  1.   0.5 ]
 [0.25 0.5  0.75]]


In [87]:
A = np.array([[2.0, -1.0, 0.0],
              [-1.0, 2.0, -1.0],
              [0.0, -1.0, 2.0]])

lam, v = np.linalg.eig(A) # Нахождение собственных значений и векторов (求特征值和特征向量)
print(lam)
print(v)

[3.41421356 2.         0.58578644]
[[-5.00000000e-01 -7.07106781e-01  5.00000000e-01]
 [ 7.07106781e-01  6.68563842e-16  7.07106781e-01]
 [-5.00000000e-01  7.07106781e-01  5.00000000e-01]]


In [88]:
b = np.array([2.0, -1.0, 3.0])
x = np.linalg.solve(A, b)  # решение Ax = b
print(x)

[1.75 1.5  2.25]
